### ISSUE TITLE
Instructions of latest version

### ISSUE THREAD

**Issue by dnlwbr** [EricVoll/ros-sharp#8]
Dear @EricVoll

first of all, thank you very much for doing all the work, bringing the code up to date. When I wanted to integrate your new version into my project I noticed a few little things in the instructions (Step 2, Option 2):
- It says "Configure RosSharpClientUWP.dll instead of RosBridgeClientUWP.dll
- It says "Configure RosSharpClient.dll" instead of RosBridgeClient.dll
- It says "Configure the NewtonSoft.dll ..." although this file does not exist. Do you mean NewtonSoft.Json.Bson.dll?

Even if the first two points are insignificant and result from the context, the last point is irritating and leaves one in doubt whether one is doing everything correctly. Especially because afterwards you emphasize again that "it is important to keep the NewtonSoft.dll in the RosSharp/Plugins folder".

Best,
Daniel

**Comment by EricVoll** [comment]
Hi @dnlwbr 

You are totally right! I'll fix that asap.
I haven't updated the readme with the newest version of the library... The demo-project is configured correctly though an should work out of the box (at least on a freshly cloned version and clean build it does in my case)

Thank you for starting the original UWP fork ;)

Best
Eric

**Comment by EricVoll** [comment]
Hi @dnlwbr 
I updated the ReadMe and fixed the issues you mentioned. Could you check if the instructions are now more clear to you?
Best,
Eric

**Comment by dnlwbr** [comment]
Hi @EricVoll 
thanks for updating the documentation. Unfortunately the mentioned file "External/NewtonSoft.Json.dll" still does not exist. 
Neither in the [RosSharp folder](https://github.com/EricVoll/ros-sharp/tree/master/Unity3D/Assets/RosSharp/Plugins/External) nor in the [Demo Project](https://github.com/EricVoll/ros-sharp/tree/master/ProjectSetup/RosSharpUnity/Assets/RosSharp/Plugins/External). I think you have deleted that file in 26f7c528358eb957c0589cf3aefdd8a2fe5e1408
Apart from that, I think the rest is clearer now.
Best
Daniel

**Comment by EricVoll** [comment]
Hi,
the AOT version of NewtonSoft.Json is in /Assets/Plugins directly, and not in the RosSharp folder.

**Comment by EricVoll** [comment]
Hi,
oh true - I forgot that this one was deleted. In an earlier version it had to be there, but with the newer version this is not the case anymore. I'll fix it.

**Comment by dnlwbr** [comment]
Okay, I get it. Thank you very much.
